load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "util",
    hdrs = [
        "include/util/enumbits.hpp",
        "include/util/uuid.hpp",
    ],
    includes = [
        "include"
    ],
    visibility = [
        "//visibility:public"
    ]
)