load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "enumbits",
    hdrs = [
        "include/enumbits/enumbits.hpp",
        "include/enumbits/atomic.hpp",
    ],
    includes = [
        "include"
    ],
    visibility = [
        "//visibility:public"
    ]
)